" DO NOT EDIT THIS FILE
" Add your own customizations in /home/p4nzer/.vim_runtime/my_configs.vim

set runtimepath+=/home/p4nzer/.vim_runtime

source /home/p4nzer/.vim_runtime/vimrcs/basic.vim
source /home/p4nzer/.vim_runtime/vimrcs/filetypes.vim
source /home/p4nzer/.vim_runtime/vimrcs/plugins_config.vim
source /home/p4nzer/.vim_runtime/vimrcs/extended.vim

try
  source /home/p4nzer/.vim_runtime/my_configs.vim
catch
endtry
