$HYDE_HYPRLAND=set #! Do not remove - HyDE marker to prevent file overwrite

#* You can freely edit this file, but make sure to not remove the above line!
#* All Files Below are yours to modify!

#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/


# ------------------------------------------------------
#TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set
#? This is only use for fallback
source = $HOME/.local/share/hyde/hyprland.conf # Fallback when HYPRLAND_CONFIG is not set
# -------------------------------------------------------

# Debug

 debug {
    disable_logs = true
    suppress_errors = true
 }

# Opens the terminal floating and sets its size to 900x600 pixels
windowrulev2 = float, class:^(kitty)$
windowrulev2 = size 900 600, class:^(kitty)$
windowrulev2 = center, class:^(kitty)$


input {
    natural_scroll = true
    touchpad {
        scroll_factor = 0.2
        natural_scroll = true
    }
}

general {
    layout = dwindle
}


#? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration // Edit this file to change your Hyprland configuration


# Group Windows

# Minimize active window by sending it to a special workspace
# Slot 1: Super+S  (original)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod, S, movetoworkspace, +0
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod, S, movetoworkspace, special:magic
bind = $mainMod, S, togglespecialworkspace, magic

# Slot 2: Super+D
bind = $mainMod, D, togglespecialworkspace, magic2
bind = $mainMod, D, movetoworkspace, +0
bind = $mainMod, D, togglespecialworkspace, magic2
bind = $mainMod, D, movetoworkspace, special:magic2
bind = $mainMod, D, togglespecialworkspace, magic2

# Slot 3: Super+F
bind = $mainMod, F, togglespecialworkspace, magic3
bind = $mainMod, F, movetoworkspace, +0
bind = $mainMod, F, togglespecialworkspace, magic3
bind = $mainMod, F, movetoworkspace, special:magic3
bind = $mainMod, F, togglespecialworkspace, magic3

# Hyprreload

bind = $mainMod SHIFT, R, exec, hyprctl reload

# Brightness Control

bind = , XF86MonBrightnessUp, exec brightnessctl set +30%

# Bluetooth

device {
    name = 2.4g-wireless-mouse
    natural_scroll = false

} 

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = HYPRCURSOR_SIZE,15
